from __future__ import annotations

SCENARIO_CLASSES = {
    "PATCH_READY_STATEMENT",
    "PATCH_READY_WRAPPER_COLLAPSE",
    "PATCH_BLOCKED_SECURITY",
    "PATCH_BLOCKED_SEMANTIC",
    "PATCH_BLOCKED_TEMPLATE_OR_UNSUPPORTED",
}

ROADMAP_STAGES = {"BASELINE", "NEXT", "FUTURE", "EXTENSION"}

ROADMAP_THEMES = {
    "STATEMENT_PATCH",
    "WRAPPER_COLLAPSE",
    "DYNAMIC_TEMPLATE",
    "SECURITY_GUARDRAIL",
    "DML_BOUNDARY",
    "AGGREGATION_SEMANTICS",
    "CTE_ENABLEMENT",
    "COMPLEX_QUERY_SHAPE",
    "COMPLEX_DYNAMIC",
}

VALIDATE_STATUSES = {"PASS", "NEED_MORE_PARAMS", "FAIL"}
SEMANTIC_TARGETS = {"PASS", "UNCERTAIN", "BLOCKED", "FAIL"}
PATCHABILITY_TARGETS = {"READY", "REVIEW", "BLOCKED"}
VALIDATE_EVIDENCE_MODES = {"compare_disabled", "exact_match_improved", "rowcount_mismatch"}
BLOCKER_FAMILIES = {"READY", "SECURITY", "SEMANTIC", "TEMPLATE_UNSUPPORTED"}
