from __future__ import annotations

from .frozen_baselines import FROZEN_BASELINE_SPECS
from .static_alias_projection_cleanup import STATIC_ALIAS_PROJECTION_CLEANUP_SPEC
from .static_include_wrapper_collapse import STATIC_INCLUDE_WRAPPER_COLLAPSE_SPEC

REGISTERED_PATCH_FAMILY_SPECS = (
    STATIC_INCLUDE_WRAPPER_COLLAPSE_SPEC,
    STATIC_ALIAS_PROJECTION_CLEANUP_SPEC,
    *FROZEN_BASELINE_SPECS,
)

__all__ = [
    "FROZEN_BASELINE_SPECS",
    "REGISTERED_PATCH_FAMILY_SPECS",
    "STATIC_ALIAS_PROJECTION_CLEANUP_SPEC",
    "STATIC_INCLUDE_WRAPPER_COLLAPSE_SPEC",
]
