from __future__ import annotations

TARGET_SHAPE_FAMILY = "IF_GUARDED_FILTER_STATEMENT"
STATIC_INCLUDE_SHAPE_FAMILY = "STATIC_INCLUDE_ONLY"
MULTI_FRAGMENT_INCLUDE_SHAPE_FAMILY = "MULTI_FRAGMENT_INCLUDE"
STATIC_STATEMENT_SHAPE_FAMILY = "STATIC_STATEMENT"
STATIC_SUBQUERY_WRAPPER_SHAPE_FAMILY = "STATIC_SUBQUERY_WRAPPER"
STATIC_ALIAS_PROJECTION_SHAPE_FAMILY = "STATIC_ALIAS_PROJECTION"
DISTINCT_WRAPPER_SHAPE_FAMILY = "DISTINCT_WRAPPER"
DISTINCT_ALIAS_SHAPE_FAMILY = "DISTINCT_ALIAS"
ORDER_BY_CONSTANT_SHAPE_FAMILY = "ORDER_BY_CONSTANT"
BOOLEAN_TAUTOLOGY_SHAPE_FAMILY = "BOOLEAN_TAUTOLOGY"
IN_LIST_SINGLE_VALUE_SHAPE_FAMILY = "IN_LIST_SINGLE_VALUE"
OR_SAME_COLUMN_SHAPE_FAMILY = "OR_SAME_COLUMN"
CASE_WHEN_TRUE_SHAPE_FAMILY = "CASE_WHEN_TRUE"
COALESCE_IDENTITY_SHAPE_FAMILY = "COALESCE_IDENTITY"
EXPRESSION_FOLDING_SHAPE_FAMILY = "EXPRESSION_FOLDING"
LIMIT_LARGE_SHAPE_FAMILY = "LIMIT_LARGE"
NULL_COMPARISON_SHAPE_FAMILY = "NULL_COMPARISON"
DISTINCT_ON_SHAPE_FAMILY = "DISTINCT_ON"
EXISTS_SELF_SHAPE_FAMILY = "EXISTS_SELF"
UNION_WRAPPER_SHAPE_FAMILY = "UNION_WRAPPER"
GROUP_BY_ALIAS_SHAPE_FAMILY = "GROUP_BY_ALIAS"
GROUP_BY_HAVING_ALIAS_SHAPE_FAMILY = "GROUP_BY_HAVING_ALIAS"
GROUP_BY_WRAPPER_SHAPE_FAMILY = "GROUP_BY_WRAPPER"
HAVING_WRAPPER_SHAPE_FAMILY = "HAVING_WRAPPER"

COUNT_WRAPPER_PATCH_FAMILY = "DYNAMIC_COUNT_WRAPPER_COLLAPSE"
STATIC_INCLUDE_PATCH_FAMILY = "STATIC_INCLUDE_WRAPPER_COLLAPSE"
STATIC_STATEMENT_PATCH_FAMILY = "STATIC_STATEMENT_REWRITE"
STATIC_CTE_PATCH_FAMILY = "STATIC_CTE_INLINE"
STATIC_SUBQUERY_WRAPPER_PATCH_FAMILY = "STATIC_SUBQUERY_WRAPPER_COLLAPSE"
STATIC_ALIAS_PROJECTION_PATCH_FAMILY = "STATIC_ALIAS_PROJECTION_CLEANUP"
GROUP_BY_WRAPPER_PATCH_FAMILY = "REDUNDANT_GROUP_BY_WRAPPER"
HAVING_WRAPPER_PATCH_FAMILY = "REDUNDANT_HAVING_WRAPPER"

SEMANTIC_RISK_TAIL_SQL_KEYS = (
    "demo.test.complex.existsSubquery",
    "demo.test.complex.leftJoinWithNull",
    "demo.test.complex.fragmentMultiplePlaces",
    "demo.test.complex.chooseBasic",
)

UNSUPPORTED_STRATEGY_TAIL_SQL_KEYS = (
    "demo.test.complex.chooseWithLimit",
)

SEMANTIC_RISK_TAIL_SQL_KEY_SET = set(SEMANTIC_RISK_TAIL_SQL_KEYS)
UNSUPPORTED_STRATEGY_TAIL_SQL_KEY_SET = set(UNSUPPORTED_STRATEGY_TAIL_SQL_KEYS)

NOT_TARGET_BOUNDARY_POLICIES: dict[str, dict[str, str]] = {
    "CHOOSE_GUARDED_FILTER_EXTENSION": {
        "bucket": "promote_next",
        "description": "choose-guarded dynamic filters stay blocked today but are close to the existing if-guarded filter capability",
    },
    "PLAIN_FOREACH_INCLUDE_PREDICATE": {
        "bucket": "keep_blocked",
        "description": "plain foreach/include predicate templates remain outside current auto-patch scope",
    },
    "AMBIGUOUS_FRAGMENT_CHAIN": {
        "bucket": "keep_blocked",
        "description": "fragment chains that can render unstable SQL stay blocked until fragment-safe materialization grows",
    },
}

SAFE_BASELINE_SUBTYPE_POLICIES: dict[str, dict[str, str]] = {
    "NO_SAFE_BASELINE_CHOOSE_GUARDED_FILTER": {
        "disposition": "defer",
        "description": "supported choose-guarded filters stay blocked until a choose-aware template-preserving patch capability exists",
    },
    "NO_SAFE_BASELINE_COLLECTION_GUARDED_PREDICATE": {
        "disposition": "defer",
        "description": "collection predicates with scalar guards stay blocked until a collection-aware template-preserving capability exists",
    },
    "NO_SAFE_BASELINE_SPECULATIVE_LIMIT_ONLY": {
        "disposition": "freeze",
        "description": "speculative pagination and limit rewrites remain explicit non-goals for auto-patch",
    },
    "NO_SAFE_BASELINE_MULTI_FRAGMENT_INCLUDE": {
        "disposition": "freeze",
        "description": "multi-fragment include chains stay blocked until fragment-chain preservation becomes a first-class capability",
    },
    "NO_SAFE_BASELINE_FOREACH_INCLUDE_PREDICATE": {
        "disposition": "defer",
        "description": "foreach/include predicates move to a future collection-predicate capability track instead of this recovery lane",
    },
    "NO_SAFE_BASELINE_GROUP_BY": {
        "disposition": "freeze",
        "description": "group-by safe-baseline gaps stay blocked until a dedicated aggregate capability stage exists",
    },
}

GENERALIZATION_NOT_TARGET_PATTERN_BY_STATEMENT: dict[str, str] = {
    "demo.order.harness.findOrdersByNos": "PLAIN_FOREACH_INCLUDE_PREDICATE",
    "demo.shipment.harness.findShipmentsByOrderIds": "PLAIN_FOREACH_INCLUDE_PREDICATE",
    "demo.test.complex.multiFragmentSeparate": "AMBIGUOUS_FRAGMENT_CHAIN",
}

RECOVERED_PATCH_FAMILY_BY_STRATEGY = {
    "REMOVE_REDUNDANT_SELECT_ALIAS_RECOVERED": "DYNAMIC_FILTER_SELECT_LIST_CLEANUP",
    "REMOVE_REDUNDANT_ALIASES": "DYNAMIC_FILTER_SELECT_LIST_CLEANUP",
    "REMOVE_UNNECESSARY_ALIASES": "DYNAMIC_FILTER_SELECT_LIST_CLEANUP",
    "REMOVE_REDUNDANT_FROM_ALIAS_RECOVERED": "DYNAMIC_FILTER_FROM_ALIAS_CLEANUP",
    "REMOVE_REDUNDANT_GROUP_BY_FROM_ALIAS_RECOVERED": "GROUP_BY_FROM_ALIAS_CLEANUP",
    "REMOVE_REDUNDANT_GROUP_BY_HAVING_FROM_ALIAS_RECOVERED": "GROUP_BY_HAVING_FROM_ALIAS_CLEANUP",
    "REMOVE_REDUNDANT_DISTINCT_FROM_ALIAS_RECOVERED": "DISTINCT_FROM_ALIAS_CLEANUP",
    "REMOVE_REDUNDANT_DISTINCT_WRAPPER_RECOVERED": "REDUNDANT_DISTINCT_WRAPPER",
    "REMOVE_CONSTANT_ORDER_BY_RECOVERED": "STATIC_ORDER_BY_SIMPLIFICATION",
    "REMOVE_BOOLEAN_TAUTOLOGY_RECOVERED": "STATIC_BOOLEAN_SIMPLIFICATION",
    "SIMPLIFY_SINGLE_VALUE_IN_LIST_RECOVERED": "STATIC_IN_LIST_SIMPLIFICATION",
    "SIMPLIFY_OR_TO_IN_RECOVERED": "STATIC_OR_SIMPLIFICATION",
    "SIMPLIFY_CASE_WHEN_TRUE_RECOVERED": "STATIC_CASE_SIMPLIFICATION",
    "SIMPLIFY_COALESCE_IDENTITY_RECOVERED": "STATIC_COALESCE_SIMPLIFICATION",
    "FOLD_CONSTANT_EXPRESSION_RECOVERED": "STATIC_EXPRESSION_FOLDING",
    "REMOVE_LARGE_LIMIT_RECOVERED": "STATIC_LIMIT_OPTIMIZATION",
    "SIMPLIFY_NULL_COMPARISON_RECOVERED": "STATIC_NULL_COMPARISON",
    "SIMPLIFY_DISTINCT_ON_RECOVERED": "STATIC_DISTINCT_ON_SIMPLIFICATION",
    "REMOVE_REDUNDANT_HAVING_WRAPPER_RECOVERED": "REDUNDANT_HAVING_WRAPPER",
    "REMOVE_REDUNDANT_SUBQUERY": "DYNAMIC_FILTER_WRAPPER_COLLAPSE",
    "REMOVE_REDUNDANT_SUBQUERY_RECOVERED": "DYNAMIC_FILTER_WRAPPER_COLLAPSE",
    "REMOVE_REDUNDANT_SUBQUERY_WRAPPER": "DYNAMIC_FILTER_WRAPPER_COLLAPSE",
    "INLINE_SUBQUERY": "DYNAMIC_FILTER_WRAPPER_COLLAPSE",
    "SUBQUERY_INLINE": "DYNAMIC_FILTER_WRAPPER_COLLAPSE",
    "SUBQUERY_UNNEST": "DYNAMIC_FILTER_WRAPPER_COLLAPSE",
    "INLINE_CTE": STATIC_CTE_PATCH_FAMILY,
    "CTE_INLINE": STATIC_CTE_PATCH_FAMILY,
}

SUPPORTED_STATIC_SHAPE_FAMILIES = {
    STATIC_INCLUDE_SHAPE_FAMILY,
    MULTI_FRAGMENT_INCLUDE_SHAPE_FAMILY,
    STATIC_STATEMENT_SHAPE_FAMILY,
    STATIC_SUBQUERY_WRAPPER_SHAPE_FAMILY,
    STATIC_ALIAS_PROJECTION_SHAPE_FAMILY,
    DISTINCT_WRAPPER_SHAPE_FAMILY,
    DISTINCT_ALIAS_SHAPE_FAMILY,
    ORDER_BY_CONSTANT_SHAPE_FAMILY,
    BOOLEAN_TAUTOLOGY_SHAPE_FAMILY,
    IN_LIST_SINGLE_VALUE_SHAPE_FAMILY,
    OR_SAME_COLUMN_SHAPE_FAMILY,
    CASE_WHEN_TRUE_SHAPE_FAMILY,
    COALESCE_IDENTITY_SHAPE_FAMILY,
    EXPRESSION_FOLDING_SHAPE_FAMILY,
    LIMIT_LARGE_SHAPE_FAMILY,
    NULL_COMPARISON_SHAPE_FAMILY,
    DISTINCT_ON_SHAPE_FAMILY,
    EXISTS_SELF_SHAPE_FAMILY,
    UNION_WRAPPER_SHAPE_FAMILY,
    GROUP_BY_ALIAS_SHAPE_FAMILY,
    GROUP_BY_WRAPPER_SHAPE_FAMILY,
    HAVING_WRAPPER_SHAPE_FAMILY,
    GROUP_BY_HAVING_ALIAS_SHAPE_FAMILY,
}

SHAPE_NORMALIZED_PATCH_FAMILY_OVERRIDES: dict[tuple[str, str], str] = {
    ("IF_GUARDED_COUNT_WRAPPER", "DYNAMIC_FILTER_WRAPPER_COLLAPSE"): COUNT_WRAPPER_PATCH_FAMILY,
    (STATIC_INCLUDE_SHAPE_FAMILY, "DYNAMIC_FILTER_WRAPPER_COLLAPSE"): STATIC_INCLUDE_PATCH_FAMILY,
    (STATIC_SUBQUERY_WRAPPER_SHAPE_FAMILY, "DYNAMIC_FILTER_WRAPPER_COLLAPSE"): STATIC_SUBQUERY_WRAPPER_PATCH_FAMILY,
    (GROUP_BY_WRAPPER_SHAPE_FAMILY, "DYNAMIC_FILTER_WRAPPER_COLLAPSE"): GROUP_BY_WRAPPER_PATCH_FAMILY,
    (HAVING_WRAPPER_SHAPE_FAMILY, "DYNAMIC_FILTER_WRAPPER_COLLAPSE"): HAVING_WRAPPER_PATCH_FAMILY,
    (STATIC_ALIAS_PROJECTION_SHAPE_FAMILY, "DYNAMIC_FILTER_SELECT_LIST_CLEANUP"): STATIC_ALIAS_PROJECTION_PATCH_FAMILY,
    (DISTINCT_WRAPPER_SHAPE_FAMILY, "DYNAMIC_FILTER_WRAPPER_COLLAPSE"): "REDUNDANT_DISTINCT_WRAPPER",
    (GROUP_BY_ALIAS_SHAPE_FAMILY, "DYNAMIC_FILTER_SELECT_LIST_CLEANUP"): "GROUP_BY_FROM_ALIAS_CLEANUP",
    (EXISTS_SELF_SHAPE_FAMILY, "DYNAMIC_FILTER_WRAPPER_COLLAPSE"): "STATIC_EXISTS_REWRITE",
    (UNION_WRAPPER_SHAPE_FAMILY, "DYNAMIC_FILTER_WRAPPER_COLLAPSE"): "STATIC_UNION_COLLAPSE",
    (STATIC_STATEMENT_SHAPE_FAMILY, "DYNAMIC_FILTER_WRAPPER_COLLAPSE"): STATIC_STATEMENT_PATCH_FAMILY,
    (STATIC_STATEMENT_SHAPE_FAMILY, "DYNAMIC_FILTER_SELECT_LIST_CLEANUP"): STATIC_STATEMENT_PATCH_FAMILY,
    (STATIC_STATEMENT_SHAPE_FAMILY, "DYNAMIC_FILTER_FROM_ALIAS_CLEANUP"): STATIC_STATEMENT_PATCH_FAMILY,
}

SHAPE_SPECIFIC_STRATEGY_PATCH_FAMILIES: dict[str, dict[str, str]] = {
    "IF_GUARDED_COUNT_WRAPPER": {
        "STRUCTURE_SIMPLIFICATION": COUNT_WRAPPER_PATCH_FAMILY,
        "SUBQUERY_REMOVAL": COUNT_WRAPPER_PATCH_FAMILY,
        "REMOVE_REDUNDANT_SUBQUERY": COUNT_WRAPPER_PATCH_FAMILY,
    },
    DISTINCT_WRAPPER_SHAPE_FAMILY: {
        "REMOVE_REDUNDANT_DISTINCT_WRAPPER_RECOVERED": "REDUNDANT_DISTINCT_WRAPPER",
    },
    DISTINCT_ALIAS_SHAPE_FAMILY: {
        "REMOVE_REDUNDANT_DISTINCT_FROM_ALIAS_RECOVERED": "DISTINCT_FROM_ALIAS_CLEANUP",
        "DISTINCT_FROM_ALIAS": "DISTINCT_FROM_ALIAS_CLEANUP",
    },
    ORDER_BY_CONSTANT_SHAPE_FAMILY: {
        "REMOVE_CONSTANT_ORDER_BY_RECOVERED": "STATIC_ORDER_BY_SIMPLIFICATION",
        "ORDER_BY_REWRITE": "STATIC_ORDER_BY_SIMPLIFICATION",
        "SORT": "STATIC_ORDER_BY_SIMPLIFICATION",
    },
    BOOLEAN_TAUTOLOGY_SHAPE_FAMILY: {
        "REMOVE_BOOLEAN_TAUTOLOGY_RECOVERED": "STATIC_BOOLEAN_SIMPLIFICATION",
        "REMOVE_TAUTOLOGY": "STATIC_BOOLEAN_SIMPLIFICATION",
    },
    IN_LIST_SINGLE_VALUE_SHAPE_FAMILY: {
        "SIMPLIFY_SINGLE_VALUE_IN_LIST_RECOVERED": "STATIC_IN_LIST_SIMPLIFICATION",
        "SIMPLIFY_SINGLE_VALUE_IN_CLAUSE": "STATIC_IN_LIST_SIMPLIFICATION",
    },
    OR_SAME_COLUMN_SHAPE_FAMILY: {
        "SIMPLIFY_OR_TO_IN_RECOVERED": "STATIC_OR_SIMPLIFICATION",
        "OR_TO_IN": "STATIC_OR_SIMPLIFICATION",
    },
    CASE_WHEN_TRUE_SHAPE_FAMILY: {
        "SIMPLIFY_CASE_WHEN_TRUE_RECOVERED": "STATIC_CASE_SIMPLIFICATION",
        "CASE_SIMPLIFICATION": "STATIC_CASE_SIMPLIFICATION",
    },
    COALESCE_IDENTITY_SHAPE_FAMILY: {
        "SIMPLIFY_COALESCE_IDENTITY_RECOVERED": "STATIC_COALESCE_SIMPLIFICATION",
        "COALESCE_SIMPLIFICATION": "STATIC_COALESCE_SIMPLIFICATION",
    },
    EXPRESSION_FOLDING_SHAPE_FAMILY: {
        "FOLD_CONSTANT_EXPRESSION_RECOVERED": "STATIC_EXPRESSION_FOLDING",
        "EXPRESSION_FOLDING": "STATIC_EXPRESSION_FOLDING",
    },
    LIMIT_LARGE_SHAPE_FAMILY: {
        "REMOVE_LARGE_LIMIT_RECOVERED": "STATIC_LIMIT_OPTIMIZATION",
        "REMOVE_INVALID_LIMIT": "STATIC_LIMIT_OPTIMIZATION",
    },
    NULL_COMPARISON_SHAPE_FAMILY: {
        "SIMPLIFY_NULL_COMPARISON_RECOVERED": "STATIC_NULL_COMPARISON",
        "NULL_COMPARISON_FIX": "STATIC_NULL_COMPARISON",
        "NULL_COMPARISON": "STATIC_NULL_COMPARISON",
    },
    DISTINCT_ON_SHAPE_FAMILY: {
        "SIMPLIFY_DISTINCT_ON_RECOVERED": "STATIC_DISTINCT_ON_SIMPLIFICATION",
        "SEMANTIC_PRESERVING": "STATIC_DISTINCT_ON_SIMPLIFICATION",
        "SAFE_DISTINCT_ON_SIMPLIFICATION": "STATIC_DISTINCT_ON_SIMPLIFICATION",
    },
    EXISTS_SELF_SHAPE_FAMILY: {
        "SAFE_EXISTS_REWRITE": "STATIC_EXISTS_REWRITE",
        "REDUNDANT_SUBQUERY_REMOVAL": "STATIC_EXISTS_REWRITE",
        "REMOVE_REDUNDANT_EXISTS": "STATIC_EXISTS_REWRITE",
    },
    UNION_WRAPPER_SHAPE_FAMILY: {
        "SAFE_UNION_COLLAPSE": "STATIC_UNION_COLLAPSE",
        "REMOVE_REDUNDANT_SUBQUERY_WRAPPER": "STATIC_UNION_COLLAPSE",
    },
    STATIC_INCLUDE_SHAPE_FAMILY: {
        "INLINE_SUBQUERY": STATIC_INCLUDE_PATCH_FAMILY,
        "SUBQUERY_REMOVAL": STATIC_INCLUDE_PATCH_FAMILY,
        "REMOVE_REDUNDANT_SUBQUERY": STATIC_INCLUDE_PATCH_FAMILY,
    },
    STATIC_SUBQUERY_WRAPPER_SHAPE_FAMILY: {
        "INLINE_SUBQUERY": STATIC_SUBQUERY_WRAPPER_PATCH_FAMILY,
        "SUBQUERY_REMOVAL": STATIC_SUBQUERY_WRAPPER_PATCH_FAMILY,
        "REMOVE_REDUNDANT_SUBQUERY": STATIC_SUBQUERY_WRAPPER_PATCH_FAMILY,
        "FLATTEN_SUBQUERY": STATIC_SUBQUERY_WRAPPER_PATCH_FAMILY,
        "STRUCTURE_PRESERVING": STATIC_SUBQUERY_WRAPPER_PATCH_FAMILY,
    },
    GROUP_BY_WRAPPER_SHAPE_FAMILY: {
        "INLINE_SUBQUERY": GROUP_BY_WRAPPER_PATCH_FAMILY,
        "SUBQUERY_REMOVAL": GROUP_BY_WRAPPER_PATCH_FAMILY,
        "REMOVE_REDUNDANT_SUBQUERY": GROUP_BY_WRAPPER_PATCH_FAMILY,
        "REMOVE_REDUNDANT_SUBQUERY_RECOVERED": GROUP_BY_WRAPPER_PATCH_FAMILY,
    },
    HAVING_WRAPPER_SHAPE_FAMILY: {
        "INLINE_SUBQUERY": HAVING_WRAPPER_PATCH_FAMILY,
        "SUBQUERY_REMOVAL": HAVING_WRAPPER_PATCH_FAMILY,
        "REMOVE_REDUNDANT_SUBQUERY": HAVING_WRAPPER_PATCH_FAMILY,
        "REMOVE_REDUNDANT_SUBQUERY_RECOVERED": HAVING_WRAPPER_PATCH_FAMILY,
    },
    STATIC_ALIAS_PROJECTION_SHAPE_FAMILY: {
        "REMOVE_REDUNDANT_SELECT_ALIAS_RECOVERED": STATIC_ALIAS_PROJECTION_PATCH_FAMILY,
        "REMOVE_REDUNDANT_ALIASES": STATIC_ALIAS_PROJECTION_PATCH_FAMILY,
        "REMOVE_UNNECESSARY_ALIASES": STATIC_ALIAS_PROJECTION_PATCH_FAMILY,
    },
    GROUP_BY_ALIAS_SHAPE_FAMILY: {
        "REMOVE_REDUNDANT_GROUP_BY_FROM_ALIAS_RECOVERED": "GROUP_BY_FROM_ALIAS_CLEANUP",
        "GROUP_BY_FROM_ALIAS": "GROUP_BY_FROM_ALIAS_CLEANUP",
    },
    STATIC_STATEMENT_SHAPE_FAMILY: {
        "REMOVE_REDUNDANT_SUBQUERY": STATIC_STATEMENT_PATCH_FAMILY,
        "INLINE_SUBQUERY": STATIC_STATEMENT_PATCH_FAMILY,
        "INLINE_CTE": STATIC_CTE_PATCH_FAMILY,
        "CTE_INLINE": STATIC_CTE_PATCH_FAMILY,
    },
}
