"""Diagnose stage: scan MyBatis mappers and collect diagnostic information.

This stage combines:
1. Scan - parse XML mappers, extract SQL units, generate branches
2. Baseline - optional EXPLAIN analysis and performance collection

The diagnose stage is the first stage in the workflow and produces
the SQL units that subsequent stages (optimize, validate, apply) will process.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from ..contracts import ContractValidator
from ..errors import StageError
from ..io_utils import write_jsonl
from ..manifest import log_event
from ..platforms.sql.rules import evaluate_rules
from ..progress import get_progress_reporter
from . import scan as scan_stage
from .preflight_check import check_and_prepare


def execute(
    config: dict[str, Any], run_dir: Path, validator: ContractValidator
) -> list[dict[str, Any]]:
    """Execute diagnose stage: scan + optional baseline collection.

    This stage:
    1. Runs preflight check to validate DB config and gather strategy info
    2. Calls scan_stage.execute() to parse XML and get SQL units
    3. Branches are already generated by scan stage
    4. Optionally runs baseline diagnostics if DB is reachable
    5. Writes diagnostic report to run directory
    6. Writes preflight info for Skill to read

    Args:
        config: Configuration dict
        run_dir: Run directory path
        validator: Contract validator

    Returns:
        List of SQL units with diagnostic information

    Raises:
        StageError: If scan fails or produces no SQL units
    """
    manifest_path = run_dir / "manifest.jsonl"
    reporter = get_progress_reporter()

    # Step 0: Run preflight check and write info for Skill
    reporter.report_info("Diagnose: Checking configuration...")
    preflight_info = check_and_prepare(config)

    # Write preflight info for Skill to read (for strategy prompting)
    preflight_path = run_dir / "preflight.json"
    with open(preflight_path, "w", encoding="utf-8") as f:
        json.dump(preflight_info, f, ensure_ascii=False, indent=2)

    # Check if DB is properly configured - block if not
    if not preflight_info["db_configured"]:
        reporter.report_warning(
            "Diagnose: DB DSN not configured - database connection required for diagnosis"
        )
        print("\n" + "=" * 60, file=sys.stderr)
        print("[ERROR] 数据库连接未配置", file=sys.stderr)
        print("=" * 60, file=sys.stderr)
        print("\n要运行诊断，需要配置数据库连接。", file=sys.stderr)
        print("请在 sqlopt.yml 中配置:", file=sys.stderr)
        print("  db:", file=sys.stderr)
        print("    platform: postgresql  # 或 mysql", file=sys.stderr)
        print("    dsn: postgresql://user:password@host:5432/dbname", file=sys.stderr)
        print("\n或设置环境变量: SQLOPT_DSN", file=sys.stderr)
        print("=" * 60, file=sys.stderr)
        raise StageError(
            "database connection required for diagnosis but DSN not configured",
            reason_code="DB_CONFIG_REQUIRED",
        )
    elif not preflight_info["db_reachable"] and preflight_info["db_strategy"] == "full":
        reporter.report_warning(
            "Diagnose: DB unreachable but strategy is 'full', will prompt for choice"
        )

    target_sql_ids = config.get("target_sql_ids")
    target_files = None

    if target_sql_ids:
        from ..application.sql_id_indexer import (
            load_index,
            lookup_files,
            is_index_valid,
        )

        project_root = Path(
            str((config.get("project", {}) or {}).get("root_path") or ".")
        ).resolve()
        index_path = project_root / ".sqlopt" / "index.json"
        index = load_index(index_path)

        if index and is_index_valid(index, project_root):
            sql_ids_list = (
                target_sql_ids if isinstance(target_sql_ids, list) else [target_sql_ids]
            )
            found_files, missing = lookup_files(index, sql_ids_list)
            if found_files:
                target_files = list(found_files)
                print(
                    f"Index lookup: found {len(found_files)} file(s) for {len(sql_ids_list)} SQL ID(s)"
                )

    # Step 1: Execute scan stage to get SQL units
    reporter.report_info("Diagnose: Running scan stage...")
    units = scan_stage.execute(config, run_dir, validator, target_files)

    if not units:
        raise StageError(
            "diagnose produced no sql units",
            reason_code="DIAGNOSE_NO_UNITS",
        )

    # Step 2: Evaluate static rules on each SQL unit
    reporter.report_info("Diagnose: Evaluating static rules...")
    units = _evaluate_static_rules(units, config)

    # Step 3: Run optional baseline diagnostics
    branch_cfg = config.get("branch", {})
    baseline_enabled = branch_cfg.get("diagnose", True)

    if baseline_enabled and _is_db_reachable(config):
        reporter.report_info("Diagnose: Running baseline diagnostics...")
        units = _run_baseline_diagnostics(units, config, run_dir, manifest_path)
    else:
        reporter.report_info("Diagnose: Skipping baseline (disabled or DB unreachable)")

    # Step 3: Write diagnostic report
    _write_diagnostic_report(units, run_dir)

    # Step 4: Log completion
    total_units = len(units)
    units_with_problems = sum(1 for u in units if u.get("problemBranchCount", 0) > 0)

    log_event(
        manifest_path,
        "diagnose",
        "done",
        {
            "totalUnits": total_units,
            "unitsWithProblems": units_with_problems,
            "baselineEnabled": baseline_enabled,
        },
    )

    reporter.report_info(
        f"Diagnose complete: {total_units} SQL units analyzed, "
        f"{units_with_problems} with potential issues"
    )

    return units


def _evaluate_static_rules(
    units: list[dict[str, Any]],
    config: dict[str, Any],
) -> list[dict[str, Any]]:
    """Evaluate static rules on SQL units.

    This adds rule evaluation results to each SQL unit, including:
    - ruleIssues: List of detected issues
    - ruleSuggestions: List of improvement suggestions
    - ruleVerdict: Overall verdict (NOOP, CAN_IMPROVE)
    - triggeredRules: List of triggered rule metadata

    Args:
        units: List of SQL units from scan stage
        config: Configuration dict

    Returns:
        List of SQL units with rule evaluation results
    """
    for unit in units:
        try:
            rule_result = evaluate_rules(unit, config)
            unit["ruleIssues"] = rule_result.get("issues", [])
            unit["ruleSuggestions"] = rule_result.get("suggestions", [])
            unit["ruleVerdict"] = rule_result.get("verdict", "NOOP")
            unit["triggeredRules"] = rule_result.get("triggeredRules", [])
        except Exception:
            # On error, set default values
            unit["ruleIssues"] = []
            unit["ruleSuggestions"] = []
            unit["ruleVerdict"] = "NOOP"
            unit["triggeredRules"] = []

    return units


def _is_db_reachable(config: dict[str, Any]) -> bool:
    """Check if database is reachable by attempting an actual connection.

    Args:
        config: Configuration dict

    Returns:
        True if database connection can be established, False otherwise
    """
    db_cfg = config.get("db", {})
    dsn = db_cfg.get("dsn")

    if not dsn:
        return False

    platform = db_cfg.get("platform", "postgresql").lower()

    try:
        if platform == "mysql":
            import pymysql

            conn = pymysql.connect(
                dsn,
                connect_timeout=5,
                read_timeout=5,
                write_timeout=5,
            )
            conn.close()
            return True
        else:
            # PostgreSQL
            try:
                import psycopg

                conn = psycopg.connect(dsn, connect_timeout=5)
                conn.close()
                return True
            except ImportError:
                import psycopg2

                conn = psycopg2.connect(dsn, connect_timeout=5)
                conn.close()
                return True
    except Exception:
        return False


def _run_baseline_diagnostics(
    units: list[dict[str, Any]],
    config: dict[str, Any],
    run_dir: Path,
    manifest_path: Path,
) -> list[dict[str, Any]]:
    """Run baseline diagnostics on SQL units.

    Args:
        units: List of SQL units
        config: Configuration dict
        run_dir: Run directory path
        manifest_path: Path to manifest file

    Returns:
        List of SQL units with baseline diagnostic information
    """
    from ..adapters.branch_diagnose import diagnose_branches

    branch_cfg = config.get("branch", {})
    diagnose_enabled = branch_cfg.get("diagnose", True)

    if not diagnose_enabled:
        return units

    for unit in units:
        branches = unit.get("branches", [])
        if not branches:
            continue

        # Diagnose branches (EXPLAIN analysis)
        try:
            branches = diagnose_branches(branches, config)
            unit["branches"] = branches
        except Exception as e:
            # Log error but continue
            log_event(
                manifest_path,
                "diagnose",
                "baseline_warning",
                {
                    "sqlKey": unit.get("sqlKey"),
                    "error": str(e),
                },
            )
            continue

        # Count problematic branches
        problem_branches = [
            b for b in branches if b.get("baseline", {}).get("problematic", False)
        ]
        unit["problemBranchCount"] = len(problem_branches)

        # Determine if this SQL needs optimization
        unit["needsOptimization"] = len(problem_branches) > 0

    # Write updated units with baseline info to diagnose.sqlunits.jsonl
    units_path = run_dir / "diagnose.sqlunits.jsonl"
    write_jsonl(units_path, units)

    # Also update scan.sqlunits.jsonl for backward compatibility
    scan_units_path = run_dir / "scan.sqlunits.jsonl"
    write_jsonl(scan_units_path, units)

    return units


def _write_diagnostic_report(
    units: list[dict[str, Any]],
    run_dir: Path,
) -> None:
    """Write diagnostic report to run directory.

    Args:
        units: List of SQL units
        run_dir: Run directory path
    """
    report_path = run_dir / "diagnose.report.json"

    # Build summary statistics
    total_units = len(units)
    total_branches = sum(u.get("branchCount", 0) for u in units)
    problem_units = [u for u in units if u.get("problemBranchCount", 0) > 0]
    problem_branches = sum(u.get("problemBranchCount", 0) for u in units)

    # Categorize issues
    issue_categories: dict[str, int] = {}
    for unit in units:
        for branch in unit.get("branches", []):
            baseline = branch.get("baseline", {})
            if baseline.get("problematic"):
                scan_type = baseline.get("type", "UNKNOWN")
                issue_categories[scan_type] = issue_categories.get(scan_type, 0) + 1

    report = {
        "summary": {
            "totalUnits": total_units,
            "totalBranches": total_branches,
            "problemUnits": len(problem_units),
            "problemBranches": problem_branches,
            "issueCategories": issue_categories,
        },
        "units": [
            {
                "sqlKey": u.get("sqlKey"),
                "statementId": u.get("statementId"),
                "namespace": u.get("namespace"),
                "branchCount": u.get("branchCount", 0),
                "problemBranchCount": u.get("problemBranchCount", 0),
                "needsOptimization": u.get("needsOptimization", False),
                "metadata": u.get("metadata", {}),
                "branches": [
                    {
                        "id": b.get("id"),
                        "type": b.get("type"),
                        "conditions": b.get("conditions", {}),
                        "sql": b.get("sql", ""),
                        "baseline": b.get("baseline", {}),
                    }
                    for b in u.get("branches", [])
                ],
            }
            for u in units
        ],
    }

    with report_path.open("w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)
