"""Diagnose stage: scan MyBatis mappers and collect diagnostic information.

This stage combines:
1. Scan - parse XML mappers, extract SQL units, generate branches
2. Baseline - optional EXPLAIN analysis and performance collection

The diagnose stage is the first stage in the workflow and produces
the SQL units that subsequent stages (optimize, validate, apply) will process.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ..contracts import ContractValidator
from ..errors import StageError
from ..io_utils import write_jsonl
from ..manifest import log_event
from ..progress import get_progress_reporter
from . import scan as scan_stage


def execute(
    config: dict[str, Any], run_dir: Path, validator: ContractValidator
) -> list[dict[str, Any]]:
    """Execute diagnose stage: scan + optional baseline collection.

    This stage:
    1. Calls scan_stage.execute() to parse XML and get SQL units
    2. Branches are already generated by scan stage
    3. Optionally runs baseline diagnostics if DB is reachable
    4. Writes diagnostic report to run directory

    Args:
        config: Configuration dict
        run_dir: Run directory path
        validator: Contract validator

    Returns:
        List of SQL units with diagnostic information

    Raises:
        StageError: If scan fails or produces no SQL units
    """
    manifest_path = run_dir / "manifest.jsonl"
    reporter = get_progress_reporter()

    # Step 1: Execute scan stage to get SQL units
    reporter.report_info("Diagnose: Running scan stage...")
    units = scan_stage.execute(config, run_dir, validator)

    if not units:
        raise StageError(
            "diagnose produced no sql units",
            reason_code="DIAGNOSE_NO_UNITS",
        )

    # Step 2: Run optional baseline diagnostics
    diagnose_cfg = config.get("diagnose", {})
    baseline_enabled = diagnose_cfg.get("baseline_enabled", True)

    if baseline_enabled and _is_db_reachable(config):
        reporter.report_info("Diagnose: Running baseline diagnostics...")
        units = _run_baseline_diagnostics(units, config, run_dir, manifest_path)
    else:
        reporter.report_info("Diagnose: Skipping baseline (disabled or DB unreachable)")

    # Step 3: Write diagnostic report
    _write_diagnostic_report(units, run_dir)

    # Step 4: Log completion
    total_units = len(units)
    units_with_problems = sum(1 for u in units if u.get("problemBranchCount", 0) > 0)

    log_event(
        manifest_path,
        "diagnose",
        "done",
        {
            "totalUnits": total_units,
            "unitsWithProblems": units_with_problems,
            "baselineEnabled": baseline_enabled,
        },
    )

    reporter.report_info(
        f"Diagnose complete: {total_units} SQL units analyzed, "
        f"{units_with_problems} with potential issues"
    )

    return units


def _is_db_reachable(config: dict[str, Any]) -> bool:
    """Check if database is reachable.

    Args:
        config: Configuration dict

    Returns:
        True if database connection can be established, False otherwise
    """
    db_cfg = config.get("db", {})
    dsn = db_cfg.get("dsn")

    if not dsn:
        return False

    try:
        # Try to get the appropriate connection function
        platform = db_cfg.get("platform", "postgresql").lower()

        if platform == "mysql":
            try:
                import pymysql  # noqa: F401
            except ImportError:
                try:
                    import mysql.connector  # noqa: F401
                except ImportError:
                    return False
        else:
            try:
                import psycopg  # noqa: F401
            except ImportError:
                try:
                    import psycopg2  # noqa: F401
                except ImportError:
                    return False

        return True
    except Exception:
        return False


def _run_baseline_diagnostics(
    units: list[dict[str, Any]],
    config: dict[str, Any],
    run_dir: Path,
    manifest_path: Path,
) -> list[dict[str, Any]]:
    """Run baseline diagnostics on SQL units.

    Args:
        units: List of SQL units
        config: Configuration dict
        run_dir: Run directory path
        manifest_path: Path to manifest file

    Returns:
        List of SQL units with baseline diagnostic information
    """
    from ..adapters.branch_diagnose import diagnose_branches

    branch_cfg = config.get("branch", {})
    diagnose_enabled = branch_cfg.get("diagnose", True)

    if not diagnose_enabled:
        return units

    for unit in units:
        branches = unit.get("branches", [])
        if not branches:
            continue

        # Diagnose branches (EXPLAIN analysis)
        try:
            branches = diagnose_branches(branches, config)
            unit["branches"] = branches
        except Exception as e:
            # Log error but continue
            log_event(
                manifest_path,
                "diagnose",
                "baseline_warning",
                {
                    "sqlKey": unit.get("sqlKey"),
                    "error": str(e),
                },
            )
            continue

        # Count problematic branches
        problem_branches = [
            b for b in branches if b.get("baseline", {}).get("problematic", False)
        ]
        unit["problemBranchCount"] = len(problem_branches)

        # Determine if this SQL needs optimization
        unit["needsOptimization"] = len(problem_branches) > 0

    # Write updated units with baseline info
    units_path = run_dir / "diagnose.sqlunits.jsonl"
    write_jsonl(units_path, units)

    return units


def _write_diagnostic_report(
    units: list[dict[str, Any]],
    run_dir: Path,
) -> None:
    """Write diagnostic report to run directory.

    Args:
        units: List of SQL units
        run_dir: Run directory path
    """
    report_path = run_dir / "diagnose.report.json"

    # Build summary statistics
    total_units = len(units)
    total_branches = sum(u.get("branchCount", 0) for u in units)
    problem_units = [u for u in units if u.get("problemBranchCount", 0) > 0]
    problem_branches = sum(u.get("problemBranchCount", 0) for u in units)

    # Categorize issues
    issue_categories: dict[str, int] = {}
    for unit in units:
        for branch in unit.get("branches", []):
            baseline = branch.get("baseline", {})
            if baseline.get("problematic"):
                scan_type = baseline.get("type", "UNKNOWN")
                issue_categories[scan_type] = issue_categories.get(scan_type, 0) + 1

    report = {
        "summary": {
            "totalUnits": total_units,
            "totalBranches": total_branches,
            "problemUnits": len(problem_units),
            "problemBranches": problem_branches,
            "issueCategories": issue_categories,
        },
        "units": [
            {
                "sqlKey": u.get("sqlKey"),
                "statementId": u.get("statementId"),
                "namespace": u.get("namespace"),
                "branchCount": u.get("branchCount", 0),
                "problemBranchCount": u.get("problemBranchCount", 0),
                "needsOptimization": u.get("needsOptimization", False),
            }
            for u in units
        ],
    }

    with report_path.open("w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)
