from __future__ import annotations

STATEMENT_SQL = "STATEMENT_SQL"
STATEMENT_TEMPLATE_SAFE = "STATEMENT_TEMPLATE_SAFE"
STATEMENT_TEMPLATE_SAFE_WRAPPER_COLLAPSE = "STATEMENT_TEMPLATE_SAFE_WRAPPER_COLLAPSE"
STATEMENT_TEMPLATE_SAFE_UNION_COLLAPSE = "STATEMENT_TEMPLATE_SAFE_UNION_COLLAPSE"
STATEMENT_TEMPLATE_SAFE_EXISTS_REWRITE = "STATEMENT_TEMPLATE_SAFE_EXISTS_REWRITE"
STATEMENT_TEMPLATE_SAFE_JOIN_LEFT_TO_INNER = "STATEMENT_TEMPLATE_SAFE_JOIN_LEFT_TO_INNER"
STATEMENT_TEMPLATE_SAFE_JOIN_ELIMINATION = "STATEMENT_TEMPLATE_SAFE_JOIN_ELIMINATION"
STATEMENT_TEMPLATE_SAFE_JOIN_REORDERING = "STATEMENT_TEMPLATE_SAFE_JOIN_REORDERING"
STATEMENT_TEMPLATE_SAFE_JOIN_CONSOLIDATION = "STATEMENT_TEMPLATE_SAFE_JOIN_CONSOLIDATION"
FRAGMENT_TEMPLATE_SAFE = "FRAGMENT_TEMPLATE_SAFE"
FRAGMENT_TEMPLATE_SAFE_AUTO = "FRAGMENT_TEMPLATE_SAFE_AUTO"
UNMATERIALIZABLE = "UNMATERIALIZABLE"

TEMPLATE_SAFE_MODES = {
    STATEMENT_TEMPLATE_SAFE,
    STATEMENT_TEMPLATE_SAFE_WRAPPER_COLLAPSE,
    STATEMENT_TEMPLATE_SAFE_UNION_COLLAPSE,
    STATEMENT_TEMPLATE_SAFE_EXISTS_REWRITE,
    STATEMENT_TEMPLATE_SAFE_JOIN_LEFT_TO_INNER,
    STATEMENT_TEMPLATE_SAFE_JOIN_ELIMINATION,
    STATEMENT_TEMPLATE_SAFE_JOIN_REORDERING,
    STATEMENT_TEMPLATE_SAFE_JOIN_CONSOLIDATION,
    FRAGMENT_TEMPLATE_SAFE,
    FRAGMENT_TEMPLATE_SAFE_AUTO,
}

REASON_STATIC_STATEMENT = "STATIC_STATEMENT"
REASON_STATEMENT_INCLUDE_SAFE = "STATEMENT_INCLUDE_SAFE"
REASON_WRAPPER_QUERY_COLLAPSE_SAFE = "WRAPPER_QUERY_COLLAPSE_SAFE"
REASON_UNION_COLLAPSE_SAFE = "UNION_COLLAPSE_SAFE"
REASON_EXISTS_REWRITE_SAFE = "EXISTS_REWRITE_SAFE"
REASON_JOIN_LEFT_TO_INNER_SAFE = "JOIN_LEFT_TO_INNER_SAFE"
REASON_JOIN_ELIMINATION_SAFE = "JOIN_ELIMINATION_SAFE"
REASON_JOIN_REORDERING_SAFE = "JOIN_REORDERING_SAFE"
REASON_JOIN_CONSOLIDATION_SAFE = "JOIN_CONSOLIDATION_SAFE"
REASON_STATEMENT_TEMPLATE_REPLAY_MISMATCH = "STATEMENT_TEMPLATE_REPLAY_MISMATCH"
REASON_STATIC_FRAGMENT_SAFE = "STATIC_FRAGMENT_SAFE"
REASON_STATIC_FRAGMENT_SAFE_WITH_BINDINGS = "STATIC_FRAGMENT_SAFE_WITH_BINDINGS"
REASON_FRAGMENT_TEMPLATE_REPLAY_MISMATCH = "FRAGMENT_TEMPLATE_REPLAY_MISMATCH"
REASON_FRAGMENT_MATERIALIZATION_DISABLED = "FRAGMENT_MATERIALIZATION_DISABLED"
REASON_MULTIPLE_FRAGMENT_BINDINGS_MISMATCH = "MULTIPLE_FRAGMENT_BINDINGS_MISMATCH"
REASON_FRAGMENT_PROPERTY_CONTEXT_UNSUPPORTED = "PATCH_FRAGMENT_PROPERTY_CONTEXT_UNSUPPORTED"
REASON_DYNAMIC_SUBTREE_TOUCHED = "DYNAMIC_SUBTREE_TOUCHED"
REASON_ANCHOR_ALIGNMENT_FAILED = "ANCHOR_ALIGNMENT_FAILED"


def materialization_reason_group(reason_code: str) -> str:
    code = str(reason_code or "").strip()
    if code in {
        REASON_STATIC_STATEMENT,
        REASON_STATEMENT_INCLUDE_SAFE,
        REASON_WRAPPER_QUERY_COLLAPSE_SAFE,
        REASON_UNION_COLLAPSE_SAFE,
        REASON_EXISTS_REWRITE_SAFE,
        REASON_JOIN_LEFT_TO_INNER_SAFE,
        REASON_JOIN_ELIMINATION_SAFE,
        REASON_JOIN_REORDERING_SAFE,
        REASON_JOIN_CONSOLIDATION_SAFE,
        REASON_STATIC_FRAGMENT_SAFE,
        REASON_STATIC_FRAGMENT_SAFE_WITH_BINDINGS,
    }:
        return "PATCH_READY"
    if code == REASON_FRAGMENT_MATERIALIZATION_DISABLED:
        return "FEATURE_DISABLED"
    if code in {REASON_STATEMENT_TEMPLATE_REPLAY_MISMATCH, REASON_FRAGMENT_TEMPLATE_REPLAY_MISMATCH}:
        return "REPLAY_MISMATCH"
    if code in {REASON_MULTIPLE_FRAGMENT_BINDINGS_MISMATCH, REASON_FRAGMENT_PROPERTY_CONTEXT_UNSUPPORTED}:
        return "BINDING_COMPLEXITY"
    if code in {REASON_DYNAMIC_SUBTREE_TOUCHED, REASON_ANCHOR_ALIGNMENT_FAILED}:
        return "TEMPLATE_COMPLEXITY"
    if code:
        return "OTHER"
    return ""
